version: "3.7"

services:
  groovy-dev:
    container_name: groovy-dev
    hostname: groovy-dev.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    networks:
      groovy-dev-net:

networks:
  groovy-dev-net:
